### PR TITLE
static frame longer

### PR DESCRIPTION
**Pull request by konbraphat51**
## What needs occurred
Show static frame longer

## Check list
- [x] Code styles confirmed
- [x] Test confirmed

### CODE REVIEW

**Comment by konbraphat51** [comment]
output

**Comment by SuperHotDogCat** [comment]
> output

In the beginning, the timestamp is "to_2012_to_2012". This is weird.

**Comment by konbraphat51** [comment]
true

**Comment by konbraphat51** [comment]
output

Enabled to configure the first time stamp

**Comment by SuperHotDogCat** [comment]
> output [ output ](https://private-user-images.githubusercontent.com/101827492/294658923-7fa092d5-149d-443a-842e-d68fddf352e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1Mjg3MTAsIm5iZiI6MTcwNDUyODQxMCwicGF0aCI6Ii8xMDE4Mjc0OTIvMjk0NjU4OTIzLTdmYTA5MmQ1LTE0OWQtNDQzYS04NDJlLWQ2OGZkZGYzNTJlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwODA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUyZjk0NTNiY2QwYThlMGEzNWU5MjQ1OTAxMmM4Nzg3NGM0NDQxMzVkZTJiYjEwOWI3NTA2MDIzMDdmNGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1t00EtM_0V2BnHsVKlZkc3qYA4AjUGYzPCYjfxooQPA) [ ](https://private-user-images.githubusercontent.com/101827492/294658923-7fa092d5-149d-443a-842e-d68fddf352e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1Mjg3MTAsIm5iZiI6MTcwNDUyODQxMCwicGF0aCI6Ii8xMDE4Mjc0OTIvMjk0NjU4OTIzLTdmYTA5MmQ1LTE0OWQtNDQzYS04NDJlLWQ2OGZkZGYzNTJlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwODA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUyZjk0NTNiY2QwYThlMGEzNWU5MjQ1OTAxMmM4Nzg3NGM0NDQxMzVkZTJiYjEwOWI3NTA2MDIzMDdmNGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1t00EtM_0V2BnHsVKlZkc3qYA4AjUGYzPCYjfxooQPA)
> 
> Enabled to configure the first time stamp

I prefer` to 2012` to `* to 2012`.

**Review by SuperHotDogCat — APPROVED** [review]

**Comment by konbraphat51** [comment]
OK

**Pull request merged**
